name: Build and Deploy2

on: 
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: DEV
    env:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
      USER: ${{ secrets.USER}}
      AWS_ENVIRONMENT: DEV

    steps:
     - uses: actions/checkout@v2
     - name: Build & Zip
       run: |
         pwd 
         ls -a 
         zip -r my-function.zip funcion1.py
         ls -a
         

     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with: 
         aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY}}
         #role-duration-seconds: 2400
         aws-region: us-east-1
         role-skip-session-tagging: true

     - name: Deploy lambda function 
       run: | 
         ls -A
         aws lambda create-function \
         --function-name my-function \
         --runtime python3.9 \
         --zip-file fileb://my-function.zip \
         --handler funcion1.lambda_handler \
         --role ${{ env.USER }}